In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Cars93.csv")
df

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             56 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [ ]:
df.describe()

,Id,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000
mean,47.000000,17.125806,19.509677,21.898925,22.365591,29.086022,2.667742,143.827957,5280.645161,2332.204301,16.664516,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226
std,26.990739,8.746029,9.659430,11.030457,5.619812,5.331726,1.037363,52.374410,596.731690,496.506525,3.279370,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510
min,1.000000,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,24.000000,10.800000,12.200000,14.700000,18.000000,26.000000,1.800000,103.000000,4800.000000,1985.000000,14.500000,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000
50%,47.000000,14.700000,17.700000,19.600000,21.000000,28.000000,2.400000,140.000000,5200.000000,2340.000000,16.400000,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000
75%,70.000000,20.300000,23.300000,25.300000,25.000000,31.000000,3.300000,170.000000,5750.000000,2565.000000,18.800000,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000
max,93.000000,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000

In [ ]:
df.head()

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [ ]:
df.tail()

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [ ]:
df.isnull().sum()

Id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [ ]:
hi = df["Rear.seat.room"] = df["Rear.seat.room"].fillna("Rear.seat.room").mode()[0]
hi

26.5

In [ ]:
df.isnull().sum()

Id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         0
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [ ]:
df["Luggage.room"] = df["Luggage.room"].fillna("Luggage.room").mode()[0]

In [ ]:
df.isnull().sum()

Id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         0
Luggage.room           0
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [ ]:
df["AirBags"] = df["AirBags"].fillna("AirBags").mode()[0]
df

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,5,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,5,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,6,193,106,70,37,26.5,14.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,26.5,14.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Driver only,...,7,187,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,5,180,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,Driver only,...,4,159,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,26.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,5,184,105,69,38,26.5,14.0,3245,non-USA,Volvo 850

In [ ]:
df.isnull().sum()

Id                    0
Manufacturer          0
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               0
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
dtype: int64

find the averrage price of each manufacturer?

In [ ]:
df.groupby("Manufacturer")["Price"].mean()

Manufacturer
Acura            24.900000
Audi             33.400000
BMW              30.000000
Buick            21.625000
Cadillac         37.400000
Chevrolet        18.187500
Chrylser         18.400000
Chrysler         22.650000
Dodge            15.700000
Eagle            15.750000
Ford             14.962500
Geo              10.450000
Honda            16.466667
Hyundai          10.475000
Infiniti         47.900000
Lexus            31.600000
Lincoln          35.200000
Mazda            17.600000
Mercedes-Benz    46.900000
Mercury          14.500000
Mitsubishi       18.200000
Nissan           17.025000
Oldsmobile       17.500000
Plymouth         14.400000
Pontiac          16.140000
Saab             28.700000
Saturn           11.100000
Subaru           12.933333
Suzuki            8.600000
Toyota           17.275000
Volkswagen       18.025000
Volvo            24.700000
Name: Price, dtype: float64

In [ ]:
df["Price"].sort_values()

30     7.4
43     8.0
52     8.3
38     8.4
79     8.4
      ...
3     37.7
18    38.0
10    40.1
47    47.9
58    61.9
Name: Price, Length: 93, dtype: float64

In [ ]:
df.sort_values('Price').head(5)

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,Driver only,...,4,141,90,63,33,26.5,14.0,1845,USA,Ford Festiva
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,Driver only,...,5,168,94,63,35,26.5,14.0,2345,non-USA,Hyundai Excel
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,Driver only,...,4,164,97,66,34,26.5,14.0,2325,non-USA,Mazda 323
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,Driver only,...,4,151,93,63,34,26.5,14.0,1695,non-USA,Geo Metro
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,Driver only,...,4,146,90,60,32,26.5,14.0,2045,non-USA,Subaru Justy

find the Manufacturer of 5 seater cars?

In [ ]:
Seater = df[df["Passengers"]==5]
Seater

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,5,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,5,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90
8,9,Buick,Riviera,Midsize,26.3,26.3,26.3,19,27,Driver only,...,5,198,108,73,41,26.5,14.0,3495,USA,Buick Riviera
10,11,Cadillac,Seville,Midsize,37.5,40.1,42.7,16,25,Driver only,...,5,204,111,74,44,26.5,14.0,3935,USA,Cadillac Seville
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,Driver only,...,5,182,101,66,38,26.5,14.0,2490,USA,Chevrolet Cavalier
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,5,184,103,68,39,26.5,14.0,2785,USA,Chevrolet Corsica
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,Driver only,...,5,174,98,66,32,26.5,14.0,2270,USA,Dodge Colt
23,24,Dodge,Shadow,Small,8.4,11.3,14.2,23,29,Driver only,...,5,172,97,67,38,26.5,14.0,2670,USA,Dodge Shadow
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,Driver only,...,5,174,98,66,36,26.5,14.0,2295,USA,Eagle Summit
31,32,Ford,Escort,Small,8.4,10.1,11.9,23,30,Driver only,...,5,171,98,67,36,26.5,14.0,2530,USA,Ford Escort
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,22,27,Driver only,...,5,177,100,68,39,26.5,14.0,2690,USA,Ford Tempo
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,26.5,14.0,3325,USA,Ford Taurus
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,Driver only,...,5,168,94,63,35,26.5,14.0,2345,non-USA,Hyundai Excel
44,45,Hyundai,Elantra,Small,9.0,10.0,11.0,22,29,Driver only,...,5,172,98,66,36,26.5,14.0,2620,non-USA,Hyundai Elantra
46,47,Hyundai,Sonata,Midsize,12.4,13.9,15.3,20,27,Driver only,...,5,184,104,69,41,26.5,14.0,2885,non-USA,Hyundai Sonata
47,48,Infiniti,Q45,Midsize,45.4,47.9,50.4,17,22,Driver only,...,5,200,113,72,42,26.5,14.0,4000,non-USA,Infiniti Q45
48,49,Lexus,ES300,Midsize,27.5,28.0,28.4,18,24,Driver only,...,5,188,103,70,40,26.5,14.0,3510,non-USA,Lexus ES300
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,Driver only,...,5,172,98,66,36,26.5,14.0,2440,non-USA,Mazda Protege
54,55,Mazda,626,Compact,14.3,16.5,18.7,26,34,Driver only,...,5,184,103,69,40,26.5,14.0,2970,non-USA,Mazda 626
57,58,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,20,29,Driver only,...,5,175,105,67,34,26.5,14.0,2920,non-USA,Mercedes-Benz 190E
58,59,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19,25,Driver only,...,5,187,110,69,37,26.5,14.0,3525,non-USA,Mercedes-Benz 300E
60,61,Mercury,Cougar,Midsize,14.9,14.9,14.9,19,26,Driver only,...,5,199,113,73,38,26.5,14.0,3610,USA,Mercury Cougar
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,Driver only,...,5,172,98,67,36,26.5,14.0,2295,non-USA,Mitsubishi Mirage
62,63,Mitsubishi,Diamante,Midsize,22.4,26.1,29.9,18,24,Driver only,...,5,190,107,70,43,26.5,14.0,3730,non-USA,Mitsubishi Diamante
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,5,170,96,66,33,26.5,14.0,2545,non-USA,Nissan Sentra
64,65,Nissan,Altima,Compact,13.0,15.7,18.3,24,30,Driver only,...,5,181,103,67,40,26.5,14.0,3050,non-USA,Nissan Altima
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,5,188,104,69,41,26.5,14.0,3200,non-USA,Nissan Maxima
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,Driver only,...,5,188,103,67,39,26.5,14.0,2910,USA,Oldsmobile Achieva
68,69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,...,5,190,105,70,42,26.5,14.0,2890,USA,Oldsmobile Cutlass_Ciera
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,Driver only,...,5,181,101,66,39,26.5,14.0,2575,USA,Pontiac Sunbird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,Driver only,...,5,195,108,72,41,26.5,14.0,3450,USA,Pontiac Grand_Prix
77,78,Saab,900,Compact,20.3,28.7,37.1,20,26,Driver only,...,5,184,99,67,37,26.5,14.0,2775,non-USA,Saab 900
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,5,176,102,68,40,26.5,14.0,2495,USA,Saturn SL
80,81,Subaru,Loyale,Small,10.5,10.9,11.3,25,30,Driver only,...,5,175,97,65,35,26.5,14.0,2490,non-USA,Subaru Loyale
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,5,179,102,67,37,26.5,14.0,3085,non-USA,Subaru Legacy
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,5,162,94,65,36,26.5,14.0,2055,non-USA,Toyota Tercel
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,5,188,103,70,38,26.5,14.0,3030,non-USA,Toyota Camry
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,5,180,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,26.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,5,184,105,69,38,26.5,14.0,3245,non-USA,Volvo 850

In [ ]:
Seater["Manufacturer"]

0             Acura
1             Acura
2              Audi
8             Buick
10         Cadillac
11        Chevrolet
12        Chevrolet
22            Dodge
23            Dodge
28            Eagle
31             Ford
32             Ford
36             Ford
43          Hyundai
44          Hyundai
46          Hyundai
47         Infiniti
48            Lexus
53            Mazda
54            Mazda
57    Mercedes-Benz
58    Mercedes-Benz
60          Mercury
61       Mitsubishi
62       Mitsubishi
63           Nissan
64           Nissan
66           Nissan
67       Oldsmobile
68       Oldsmobile
73          Pontiac
75          Pontiac
77             Saab
78           Saturn
80           Subaru
81           Subaru
83           Toyota
85           Toyota
89       Volkswagen
91            Volvo
92            Volvo
Name: Manufacturer, dtype: object

In [ ]:
Seater[["Manufacturer","Model","Price"]]

     Manufacturer          Model  Price
0           Acura        Integra   15.9
1           Acura         Legend   33.9
2            Audi             90   29.1
8           Buick        Riviera   26.3
10       Cadillac        Seville   40.1
11      Chevrolet       Cavalier   13.4
12      Chevrolet        Corsica   11.4
22          Dodge           Colt    9.2
23          Dodge         Shadow   11.3
28          Eagle         Summit   12.2
31           Ford         Escort   10.1
32           Ford          Tempo   11.3
36           Ford         Taurus   20.2
43        Hyundai          Excel    8.0
44        Hyundai        Elantra   10.0
46        Hyundai         Sonata   13.9
47       Infiniti            Q45   47.9
48          Lexus          ES300   28.0
53          Mazda        Protege   11.6
54          Mazda            626   16.5
57  Mercedes-Benz           190E   31.9
58  Mercedes-Benz           300E   61.9
60        Mercury         Cougar   14.9
61     Mitsubishi         Mirage   10.3
62     Mitsubishi       Diamante   26.1
63         Nissan         Sentra   11.8
64         Nissan         Altima   15.7
66         Nissan         Maxima   21.5
67     Oldsmobile        Achieva   13.5
68     Oldsmobile  Cutlass_Ciera   16.3
73        Pontiac        Sunbird   11.1
75        Pontiac     Grand_Prix   18.5
77           Saab            900   28.7
78         Saturn             SL   11.1
80         Subaru         Loyale   10.9
81         Subaru         Legacy   19.5
83         Toyota         Tercel    9.8
85         Toyota          Camry   18.2
89     Volkswagen         Passat   20.0
91          Volvo            240   22.7
92          Volvo            850   26.7

In [ ]:
Seater[["Type","Max.Price","Min.Price"]]

       Type  Max.Price  Min.Price
0     Small       18.8       12.9
1   Midsize       38.7       29.2
2   Compact       32.3       25.9
8   Midsize       26.3       26.3
10  Midsize       42.7       37.5
11  Compact       18.3        8.5
12  Compact       11.4       11.4
22    Small       10.6        7.9
23    Small       14.2        8.4
28    Small       16.5        7.9
31    Small       11.9        8.4
32  Compact       12.2       10.4
36  Midsize       24.8       15.6
43    Small        9.2        6.8
44    Small       11.0        9.0
46  Midsize       15.3       12.4
47  Midsize       50.4       45.4
48  Midsize       28.4       27.5
53    Small       12.3       10.9
54  Compact       18.7       14.3
57  Compact       34.9       29.0
58  Midsize       80.0       43.8
60  Midsize       14.9       14.9
61    Small       12.9        7.7
62  Midsize       29.9       22.4
63    Small       14.9        8.7
64  Compact       18.3       13.0
66  Midsize       22.0       21.0
67  Compact       14.0       13.0
68  Midsize       18.4       14.2
73  Compact       12.8        9.4
75  Midsize       21.6       15.4
77  Compact       37.1       20.3
78    Small       12.9        9.2
80    Small       11.3       10.5
81  Compact       22.7       16.3
83    Small       11.8        7.8
85  Midsize       21.2       15.2
89  Compact       22.4       17.6
91  Compact       23.5       21.8
92  Midsize       28.5       24.8

In [ ]:
df["difference"] = df["Max.Price"] - df["Min.Price"]

In [ ]:
df[["difference","Max.Price","Min.Price"]]

    difference  Max.Price  Min.Price
0          5.9       18.8       12.9
1          9.5       38.7       29.2
2          6.4       32.3       25.9
3         13.8       44.6       30.8
4         12.5       36.2       23.7
..         ...        ...        ...
88         6.1       22.7       16.6
89         4.8       22.4       17.6
90         0.8       23.7       22.9
91         1.7       23.5       21.8
92         3.7       28.5       24.8

[93 rows x 3 columns]

In [ ]:
df.head()

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,193,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,186,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5

In [ ]:
df[df["MPG.highway"]>30]

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9
5,6,Buick,Century,Midsize,14.2,15.7,17.3,22,31,Driver only,...,189,105,69,41,26.5,14.0,2880,USA,Buick Century,3.1
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,Driver only,...,182,101,66,38,26.5,14.0,2490,USA,Chevrolet Cavalier,9.8
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,184,103,68,39,26.5,14.0,2785,USA,Chevrolet Corsica,0.0
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,Driver only,...,174,98,66,32,26.5,14.0,2270,USA,Dodge Colt,2.7
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,Driver only,...,174,98,66,36,26.5,14.0,2295,USA,Eagle Summit,8.6
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,Driver only,...,141,90,63,33,26.5,14.0,1845,USA,Ford Festiva,1.0
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,Driver only,...,151,93,63,34,26.5,14.0,1695,non-USA,Geo Metro,3.3
39,40,Geo,Storm,Sporty,11.5,12.5,13.5,30,36,Driver only,...,164,97,67,37,26.5,14.0,2475,non-USA,Geo Storm,2.0
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver only,...,175,100,70,39,26.5,14.0,2865,non-USA,Honda Prelude,5.7
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,173,103,67,36,26.5,14.0,2350,non-USA,Honda Civic,7.4
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver only,...,185,107,67,41,26.5,14.0,3040,non-USA,Honda Accord,7.4
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,Driver only,...,168,94,63,35,26.5,14.0,2345,non-USA,Hyundai Excel,2.4
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,Driver only,...,166,94,64,34,26.5,14.0,2285,non-USA,Hyundai Scoupe,1.9
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,Driver only,...,164,97,66,34,26.5,14.0,2325,non-USA,Mazda 323,1.7
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,Driver only,...,172,98,66,36,26.5,14.0,2440,non-USA,Mazda Protege,1.4
54,55,Mazda,626,Compact,14.3,16.5,18.7,26,34,Driver only,...,184,103,69,40,26.5,14.0,2970,non-USA,Mazda 626,4.4
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,Driver only,...,172,98,67,36,26.5,14.0,2295,non-USA,Mitsubishi Mirage,5.2
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,170,96,66,33,26.5,14.0,2545,non-USA,Nissan Sentra,6.2
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,Driver only,...,188,103,67,39,26.5,14.0,2910,USA,Oldsmobile Achieva,1.0
68,69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,...,190,105,70,42,26.5,14.0,2890,USA,Oldsmobile Cutlass_Ciera,4.2
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,Driver only,...,177,99,66,35,26.5,14.0,2350,USA,Pontiac LeMans,1.7
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,Driver only,...,181,101,66,39,26.5,14.0,2575,USA,Pontiac Sunbird,3.4
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,176,102,68,40,26.5,14.0,2495,USA,Saturn SL,3.7
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,Driver only,...,146,90,60,32,26.5,14.0,2045,non-USA,Subaru Justy,2.2
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,Driver only,...,161,93,63,34,26.5,14.0,1965,non-USA,Suzuki Swift,2.7
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,162,94,65,36,26.5,14.0,2055,non-USA,Toyota Tercel,4.0
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,174,99,69,39,26.5,14.0,2950,non-USA,Toyota Celica,8.4
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,Driver only,...,163,93,63,34,26.5,14.0,2240,non-USA,Volkswagen Fox,0.8

FIND THE MANUFACTURER AND MIN PRICE

In [ ]:
df[["Manufacturer","Min.Price"]].sort_values("Min.Price").head(10)

   Manufacturer  Min.Price
38          Geo        6.7
43      Hyundai        6.8
30         Ford        6.9
79       Subaru        7.3
82       Suzuki        7.3
52        Mazda        7.4
61   Mitsubishi        7.7
83       Toyota        7.8
28        Eagle        7.9
22        Dodge        7.9

find the airbags where drivers only?

In [ ]:
df[df["AirBags"]=="Driver only"]

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,193,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,186,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Driver only,...,187,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,180,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,Driver only,...,159,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,190,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,184,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7

In [ ]:
car = df[df["AirBags"]=="Driver only"]
car

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,193,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,186,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Driver only,...,187,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,180,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,Driver only,...,159,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,190,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,184,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7

In [ ]:
car.sort_values("Max.Price",ascending=False).head(1)

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
58,59,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19,25,Driver only,...,187,110,69,37,26.5,14.0,3525,non-USA,Mercedes-Benz 300E,36.2

In [ ]:
car.sort_values("Min.Price").head(1)

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,Driver only,...,151,93,63,34,26.5,14.0,1695,non-USA,Geo Metro,3.3

In [ ]:
df

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,177,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,193,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,186,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Driver only,...,187,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,180,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,Driver only,...,159,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,190,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,184,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7

find the average weight of the car ?

In [ ]:
df.groupby("Manufacturer")["Weight"].mean()

Manufacturer
Acura            3132.500000
Audi             3390.000000
BMW              3640.000000
Buick            3487.500000
Cadillac         3777.500000
Chevrolet        3342.500000
Chrylser         3515.000000
Chrysler         3327.500000
Dodge            3083.333333
Eagle            2892.500000
Ford             2954.375000
Geo              2085.000000
Honda            2751.666667
Hyundai          2533.750000
Infiniti         4000.000000
Lexus            3512.500000
Lincoln          3875.000000
Mazda            2873.000000
Mercedes-Benz    3222.500000
Mercury          3030.000000
Mitsubishi       3012.500000
Nissan           3223.750000
Oldsmobile       3246.250000
Plymouth         2640.000000
Pontiac          3022.000000
Saab             2775.000000
Saturn           2495.000000
Subaru           2540.000000
Suzuki           1965.000000
Toyota           2955.000000
Volkswagen       2998.750000
Volvo            3115.000000
Name: Weight, dtype: float64

In [ ]:
tesla = df.groupby("Manufacturer")["Weight"].mean()

In [ ]:
gt = df["Weight"].mean()
gt

np.float64(3072.9032258064517)

In [ ]:
df[df["Weight"] > gt]

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,195,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,180,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,193,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,186,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,200,111,74,42,26.5,14.0,3470,USA,Buick LeSabre,1.8
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,216,116,78,45,26.5,14.0,4105,USA,Buick Roadmaster,2.3
8,9,Buick,Riviera,Midsize,26.3,26.3,26.3,19,27,Driver only,...,198,108,73,41,26.5,14.0,3495,USA,Buick Riviera,0.0
9,10,Cadillac,DeVille,Large,33.0,34.7,36.3,16,25,Driver only,...,206,114,73,43,26.5,14.0,3620,USA,Cadillac DeVille,3.3
10,11,Cadillac,Seville,Midsize,37.5,40.1,42.7,16,25,Driver only,...,204,111,74,44,26.5,14.0,3935,USA,Cadillac Seville,5.2
13,14,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19,28,Driver only,...,193,101,74,43,26.5,14.0,3240,USA,Chevrolet Camaro,3.4
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,Driver only,...,198,108,71,40,26.5,14.0,3195,USA,Chevrolet Lumina,5.0
15,16,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18,23,Driver only,...,178,110,74,44,26.5,14.0,3715,USA,Chevrolet Lumina_APV,3.3
16,17,Chevrolet,Astro,Van,14.7,16.6,18.6,15,20,Driver only,...,194,111,78,42,26.5,14.0,4025,USA,Chevrolet Astro,3.9
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,214,116,77,42,26.5,14.0,3910,USA,Chevrolet Caprice,1.6
18,19,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17,25,Driver only,...,179,96,74,43,26.5,14.0,3380,USA,Chevrolet Corvette,6.9
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver only,...,203,113,74,40,26.5,14.0,3515,USA,Chrylser Concorde,0.0
20,21,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23,28,Driver only,...,183,104,68,41,26.5,14.0,3085,USA,Chrysler LeBaron,2.6
21,22,Chrysler,Imperial,Large,29.5,29.5,29.5,20,26,Driver only,...,203,110,69,44,26.5,14.0,3570,USA,Chrysler Imperial,0.0
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,17,21,Driver only,...,175,112,72,42,26.5,14.0,3705,USA,Dodge Caravan,10.8
26,27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21,27,Driver only,...,192,105,69,42,26.5,14.0,3080,USA,Dodge Dynasty,1.6
27,28,Dodge,Stealth,Sporty,18.5,25.8,33.1,18,24,Driver only,...,180,97,72,40,26.5,14.0,3805,USA,Dodge Stealth,14.6
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver only,...,202,113,74,40,26.5,14.0,3490,USA,Eagle Vision,3.7
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,15,20,Driver only,...,176,119,72,45,26.5,14.0,3735,USA,Ford Aerostar,10.8
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,192,106,71,40,26.5,14.0,3325,USA,Ford Taurus,9.2
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,212,114,78,43,26.5,14.0,3950,USA,Ford Crown_Victoria,1.6
47,48,Infiniti,Q45,Midsize,45.4,47.9,50.4,17,22,Driver only,...,200,113,72,42,26.5,14.0,4000,non-USA,Infiniti Q45,5.0
48,49,Lexus,ES300,Midsize,27.5,28.0,28.4,18,24,Driver only,...,188,103,70,40,26.5,14.0,3510,non-USA,Lexus ES300,0.9
49,50,Lexus,SC300,Midsize,34.7,35.2,35.6,18,23,Driver only,...,191,106,71,39,26.5,14.0,3515,non-USA,Lexus SC300,0.9
50,51,Lincoln,Continental,Midsize,33.3,34.3,35.3,17,26,Driver only,...,205,109,73,42,26.5,14.0,3695,USA,Lincoln Continental,2.0
51,52,Lincoln,Town_Car,Large,34.4,36.1,37.8,18,26,Driver only,...,219,117,77,45,26.5,14.0,4055,USA,Lincoln Town_Car,3.4
55,56,Mazda,MPV,Van,16.6,19.1,21.7,18,24,Driver only,...,190,110,72,39,26.5,14.0,3735,non-USA,Mazda MPV,5.1
58,59,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19,25,Driver only,...,187,110,69,37,26.5,14.0,3525,non-USA,Mercedes-Benz 300E,36.2
60,61,Mercury,Cougar,Midsize,14.9,14.9,14.9,19,26,Driver only,...,199,113,73,38,26.5,14.0,3610,USA,Mercury Cougar,0.0
62,63,Mitsubishi,Diamante,Midsize,22.4,26.1,29.9,18,24,Driver only,...,190,107,70,43,26.5,14.0,3730,non-USA,Mitsubishi Diamante,7.5
65,66,Nissan,Quest,Van,16.7,19.1,21.5,17,23,Driver only,...,190,112,74,41,26.5,14.0,4100,non-USA,Nissan Quest,4.8
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,188,104,69,41,26.5,14.0,3200,non-USA,Nissan Maxima,1.0
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,Driver only,...,194,110,74,44,26.5,14.0,3715,USA,Oldsmobile Silhouette,0.0
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,201,111,74,42,26.5,14.0,3470,USA,Oldsmobile Eighty-Eight,2.4
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver only,...,196,101,75,43,26.5,14.0,3240,USA,Pontiac Firebird,7.4
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,Driver only,...,195,108,72,41,26.5,14.0,3450,USA,Pontiac Grand_Prix,6.2
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,19,28,Driver only,...,177,111,74,43,26.5,14.0,3495,USA,Pontiac Bonneville,10.0
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,179,102,67,37,26.5,14.0,3085,non-USA,Subaru Legacy,6.4
86,87,Toyota,Previa,Van,18.9,22.7,26.6,18,22,Driver only,...,187,113,71,41,26.5,14.0,3785,non-USA,Toyota Previa,7.7
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Driver only,...,187,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,184,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7

count tha sporty car

In [ ]:
gt = df[df["Type"]=="Sporty"]

In [ ]:
gt.value_counts().sum()

np.int64(14)

In [ ]:
alokcharce = df["Area"] = df["Length"] * df["Width"]

In [ ]:
df

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9,12036
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver only,...,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5,13845
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4,12060
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8,13510
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5,12834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,Driver only,...,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1,13464
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8,12060
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,Driver only,...,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8,10494
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7,12730
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver only,...,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7,12696

In [ ]:
df.sort_values("Area",ascending=False).head(5)

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
51,52,Lincoln,Town_Car,Large,34.4,36.1,37.8,18,26,Driver only,...,117,77,45,26.5,14.0,4055,USA,Lincoln Town_Car,3.4,16863
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,116,78,45,26.5,14.0,4105,USA,Buick Roadmaster,2.3,16848
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,114,78,43,26.5,14.0,3950,USA,Ford Crown_Victoria,1.6,16536
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,116,77,42,26.5,14.0,3910,USA,Chevrolet Caprice,1.6,16478
16,17,Chevrolet,Astro,Van,14.7,16.6,18.6,15,20,Driver only,...,111,78,42,26.5,14.0,4025,USA,Chevrolet Astro,3.9,15132

In [ ]:
df[df["MPG.city"]>20]

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9,12036
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5,12834
5,6,Buick,Century,Midsize,14.2,15.7,17.3,22,31,Driver only,...,105,69,41,26.5,14.0,2880,USA,Buick Century,3.1,13041
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,Driver only,...,101,66,38,26.5,14.0,2490,USA,Chevrolet Cavalier,9.8,12012
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,103,68,39,26.5,14.0,2785,USA,Chevrolet Corsica,0.0,12512
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,Driver only,...,108,71,40,26.5,14.0,3195,USA,Chevrolet Lumina,5.0,14058
20,21,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23,28,Driver only,...,104,68,41,26.5,14.0,3085,USA,Chrysler LeBaron,2.6,12444
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,Driver only,...,98,66,32,26.5,14.0,2270,USA,Dodge Colt,2.7,11484
23,24,Dodge,Shadow,Small,8.4,11.3,14.2,23,29,Driver only,...,97,67,38,26.5,14.0,2670,USA,Dodge Shadow,5.8,11524
24,25,Dodge,Spirit,Compact,11.9,13.3,14.7,22,27,Driver only,...,104,68,39,26.5,14.0,2970,USA,Dodge Spirit,2.8,12308
26,27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21,27,Driver only,...,105,69,42,26.5,14.0,3080,USA,Dodge Dynasty,1.6,13248
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,Driver only,...,98,66,36,26.5,14.0,2295,USA,Eagle Summit,8.6,11484
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,Driver only,...,90,63,33,26.5,14.0,1845,USA,Ford Festiva,1.0,8883
31,32,Ford,Escort,Small,8.4,10.1,11.9,23,30,Driver only,...,98,67,36,26.5,14.0,2530,USA,Ford Escort,3.5,11457
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,22,27,Driver only,...,100,68,39,26.5,14.0,2690,USA,Ford Tempo,1.8,12036
33,34,Ford,Mustang,Sporty,10.8,15.9,21.0,22,29,Driver only,...,101,68,40,26.5,14.0,2850,USA,Ford Mustang,10.2,12240
34,35,Ford,Probe,Sporty,12.8,14.0,15.2,24,30,Driver only,...,103,70,38,26.5,14.0,2710,USA,Ford Probe,2.4,12530
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,106,71,40,26.5,14.0,3325,USA,Ford Taurus,9.2,13632
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,Driver only,...,93,63,34,26.5,14.0,1695,non-USA,Geo Metro,3.3,9513
39,40,Geo,Storm,Sporty,11.5,12.5,13.5,30,36,Driver only,...,97,67,37,26.5,14.0,2475,non-USA,Geo Storm,2.0,10988
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver only,...,100,70,39,26.5,14.0,2865,non-USA,Honda Prelude,5.7,12250
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,103,67,36,26.5,14.0,2350,non-USA,Honda Civic,7.4,11591
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver only,...,107,67,41,26.5,14.0,3040,non-USA,Honda Accord,7.4,12395
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,Driver only,...,94,63,35,26.5,14.0,2345,non-USA,Hyundai Excel,2.4,10584
44,45,Hyundai,Elantra,Small,9.0,10.0,11.0,22,29,Driver only,...,98,66,36,26.5,14.0,2620,non-USA,Hyundai Elantra,2.0,11352
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,Driver only,...,94,64,34,26.5,14.0,2285,non-USA,Hyundai Scoupe,1.9,10624
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,Driver only,...,97,66,34,26.5,14.0,2325,non-USA,Mazda 323,1.7,10824
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,Driver only,...,98,66,36,26.5,14.0,2440,non-USA,Mazda Protege,1.4,11352
54,55,Mazda,626,Compact,14.3,16.5,18.7,26,34,Driver only,...,103,69,40,26.5,14.0,2970,non-USA,Mazda 626,4.4,12696
59,60,Mercury,Capri,Sporty,13.3,14.1,15.0,23,26,Driver only,...,95,65,36,26.5,14.0,2450,USA,Mercury Capri,1.7,10790
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,Driver only,...,98,67,36,26.5,14.0,2295,non-USA,Mitsubishi Mirage,5.2,11524
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,96,66,33,26.5,14.0,2545,non-USA,Nissan Sentra,6.2,11220
64,65,Nissan,Altima,Compact,13.0,15.7,18.3,24,30,Driver only,...,103,67,40,26.5,14.0,3050,non-USA,Nissan Altima,5.3,12127
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,104,69,41,26.5,14.0,3200,non-USA,Nissan Maxima,1.0,12972
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,Driver only,...,103,67,39,26.5,14.0,2910,USA,Oldsmobile Achieva,1.0,12596
68,69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,...,105,70,42,26.5,14.0,2890,USA,Oldsmobile Cutlass_Ciera,4.2,13300
71,72,Plymouth,Laser,Sporty,11.4,14.4,17.4,23,30,Driver only,...,97,67,39,26.5,14.0,2640,USA,Plymouth Laser,6.0,11591
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,Driver only,...,99,66,35,26.5,14.0,2350,USA,Pontiac LeMans,1.7,11682
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,Driver only,...,101,66,39,26.5,14.0,2575,USA,Pontiac Sunbird,3.4,11946
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,102,68,40,26.5,14.0,2495,USA,Saturn SL,3.7,11968
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,Driver only,...,90,60,32,26.5,14.0,2045,non-USA,Subaru Justy,2.2,8760
80,81,Subaru,Loyale,Small,10.5,10.9,11.3,25,30,Driver only,...,97,65,35,26.5,14.0,2490,non-USA,Subaru Loyale,0.8,11375
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,102,67,37,26.5,14.0,3085,non-USA,Subaru Legacy,6.4,11993
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,Driver only,...,93,63,34,26.5,14.0,1965,non-USA,Suzuki Swift,2.7,10143
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,94,65,36,26.5,14.0,2055,non-USA,Toyota Tercel,4.0,10530
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,99,69,39,26.5,14.0,2950,non-USA,Toyota Celica,8.4,12006
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,103,70,38,26.5,14.0,3030,non-USA,Toyota Camry,6.0,13160
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,Driver only,...,93,63,34,26.5,14.0,2240,non-USA,Volkswagen Fox,0.8,10269
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,Driver only,...,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8,12060
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7,12730

In [ ]:
BMW = df["MPG.city"].mean()
BMW

np.float64(22.365591397849464)

In [ ]:
import numpy as np
df["MPG.city"] = np.where((df["MPG.city"] < BMW),df["MPG.city"] + 2, df["MPG.city"])

In [ ]:
df["MPG.city"]

0     25
1     20
2     22
3     21
4     24
      ..
88    19
89    23
90    20
91    23
92    22
Name: MPG.city, Length: 93, dtype: int64

In [ ]:
df[df["Origin"]=="USA"]

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
5,6,Buick,Century,Midsize,14.2,15.7,17.3,24,31,Driver only,...,105,69,41,26.5,14.0,2880,USA,Buick Century,3.1,13041
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,21,28,Driver only,...,111,74,42,26.5,14.0,3470,USA,Buick LeSabre,1.8,14800
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,18,25,Driver only,...,116,78,45,26.5,14.0,4105,USA,Buick Roadmaster,2.3,16848
8,9,Buick,Riviera,Midsize,26.3,26.3,26.3,21,27,Driver only,...,108,73,41,26.5,14.0,3495,USA,Buick Riviera,0.0,14454
9,10,Cadillac,DeVille,Large,33.0,34.7,36.3,18,25,Driver only,...,114,73,43,26.5,14.0,3620,USA,Cadillac DeVille,3.3,15038
10,11,Cadillac,Seville,Midsize,37.5,40.1,42.7,18,25,Driver only,...,111,74,44,26.5,14.0,3935,USA,Cadillac Seville,5.2,15096
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,Driver only,...,101,66,38,26.5,14.0,2490,USA,Chevrolet Cavalier,9.8,12012
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,103,68,39,26.5,14.0,2785,USA,Chevrolet Corsica,0.0,12512
13,14,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,21,28,Driver only,...,101,74,43,26.5,14.0,3240,USA,Chevrolet Camaro,3.4,14282
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,23,29,Driver only,...,108,71,40,26.5,14.0,3195,USA,Chevrolet Lumina,5.0,14058
15,16,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,20,23,Driver only,...,110,74,44,26.5,14.0,3715,USA,Chevrolet Lumina_APV,3.3,13172
16,17,Chevrolet,Astro,Van,14.7,16.6,18.6,17,20,Driver only,...,111,78,42,26.5,14.0,4025,USA,Chevrolet Astro,3.9,15132
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,19,26,Driver only,...,116,77,42,26.5,14.0,3910,USA,Chevrolet Caprice,1.6,16478
18,19,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,19,25,Driver only,...,96,74,43,26.5,14.0,3380,USA,Chevrolet Corvette,6.9,13246
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,22,28,Driver only,...,113,74,40,26.5,14.0,3515,USA,Chrylser Concorde,0.0,15022
20,21,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23,28,Driver only,...,104,68,41,26.5,14.0,3085,USA,Chrysler LeBaron,2.6,12444
21,22,Chrysler,Imperial,Large,29.5,29.5,29.5,22,26,Driver only,...,110,69,44,26.5,14.0,3570,USA,Chrysler Imperial,0.0,14007
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,Driver only,...,98,66,32,26.5,14.0,2270,USA,Dodge Colt,2.7,11484
23,24,Dodge,Shadow,Small,8.4,11.3,14.2,23,29,Driver only,...,97,67,38,26.5,14.0,2670,USA,Dodge Shadow,5.8,11524
24,25,Dodge,Spirit,Compact,11.9,13.3,14.7,24,27,Driver only,...,104,68,39,26.5,14.0,2970,USA,Dodge Spirit,2.8,12308
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,19,21,Driver only,...,112,72,42,26.5,14.0,3705,USA,Dodge Caravan,10.8,12600
26,27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,23,27,Driver only,...,105,69,42,26.5,14.0,3080,USA,Dodge Dynasty,1.6,13248
27,28,Dodge,Stealth,Sporty,18.5,25.8,33.1,20,24,Driver only,...,97,72,40,26.5,14.0,3805,USA,Dodge Stealth,14.6,12960
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,Driver only,...,98,66,36,26.5,14.0,2295,USA,Eagle Summit,8.6,11484
29,30,Eagle,Vision,Large,17.5,19.3,21.2,22,28,Driver only,...,113,74,40,26.5,14.0,3490,USA,Eagle Vision,3.7,14948
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,Driver only,...,90,63,33,26.5,14.0,1845,USA,Ford Festiva,1.0,8883
31,32,Ford,Escort,Small,8.4,10.1,11.9,23,30,Driver only,...,98,67,36,26.5,14.0,2530,USA,Ford Escort,3.5,11457
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,24,27,Driver only,...,100,68,39,26.5,14.0,2690,USA,Ford Tempo,1.8,12036
33,34,Ford,Mustang,Sporty,10.8,15.9,21.0,24,29,Driver only,...,101,68,40,26.5,14.0,2850,USA,Ford Mustang,10.2,12240
34,35,Ford,Probe,Sporty,12.8,14.0,15.2,24,30,Driver only,...,103,70,38,26.5,14.0,2710,USA,Ford Probe,2.4,12530
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,17,20,Driver only,...,119,72,45,26.5,14.0,3735,USA,Ford Aerostar,10.8,12672
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,23,30,Driver only,...,106,71,40,26.5,14.0,3325,USA,Ford Taurus,9.2,13632
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,20,26,Driver only,...,114,78,43,26.5,14.0,3950,USA,Ford Crown_Victoria,1.6,16536
50,51,Lincoln,Continental,Midsize,33.3,34.3,35.3,19,26,Driver only,...,109,73,42,26.5,14.0,3695,USA,Lincoln Continental,2.0,14965
51,52,Lincoln,Town_Car,Large,34.4,36.1,37.8,20,26,Driver only,...,117,77,45,26.5,14.0,4055,USA,Lincoln Town_Car,3.4,16863
59,60,Mercury,Capri,Sporty,13.3,14.1,15.0,23,26,Driver only,...,95,65,36,26.5,14.0,2450,USA,Mercury Capri,1.7,10790
60,61,Mercury,Cougar,Midsize,14.9,14.9,14.9,21,26,Driver only,...,113,73,38,26.5,14.0,3610,USA,Mercury Cougar,0.0,14527
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,Driver only,...,103,67,39,26.5,14.0,2910,USA,Oldsmobile Achieva,1.0,12596
68,69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,...,105,70,42,26.5,14.0,2890,USA,Oldsmobile Cutlass_Ciera,4.2,13300
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,20,23,Driver only,...,110,74,44,26.5,14.0,3715,USA,Oldsmobile Silhouette,0.0,14356
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,21,28,Driver only,...,111,74,42,26.5,14.0,3470,USA,Oldsmobile Eighty-Eight,2.4,14874
71,72,Plymouth,Laser,Sporty,11.4,14.4,17.4,23,30,Driver only,...,97,67,39,26.5,14.0,2640,USA,Plymouth Laser,6.0,11591
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,Driver only,...,99,66,35,26.5,14.0,2350,USA,Pontiac LeMans,1.7,11682
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,Driver only,...,101,66,39,26.5,14.0,2575,USA,Pontiac Sunbird,3.4,11946
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,21,28,Driver only,...,101,75,43,26.5,14.0,3240,USA,Pontiac Firebird,7.4,14700
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,21,27,Driver only,...,108,72,41,26.5,14.0,3450,USA,Pontiac Grand_Prix,6.2,14040
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,21,28,Driver only,...,111,74,43,26.5,14.0,3495,USA,Pontiac Bonneville,10.0,13098
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,102,68,40,26.5,14.0,2495,USA,Saturn SL,3.7,11968

In [ ]:
df

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9,12036
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,20,25,Driver only,...,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5,13845
2,3,Audi,90,Compact,25.9,29.1,32.3,22,26,Driver only,...,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4,12060
3,4,Audi,100,Midsize,30.8,37.7,44.6,21,26,Driver only,...,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8,13510
4,5,BMW,535i,Midsize,23.7,30.0,36.2,24,30,Driver only,...,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5,12834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,19,21,Driver only,...,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1,13464
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,23,30,Driver only,...,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8,12060
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,20,25,Driver only,...,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8,10494
91,92,Volvo,240,Compact,21.8,22.7,23.5,23,28,Driver only,...,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7,12730
92,93,Volvo,850,Midsize,24.8,26.7,28.5,22,28,Driver only,...,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7,12696

find any milage for each manufacturer

In [ ]:
mileage_by_manufacturer = df.groupby("Manufacturer")[["MPG.city", "MPG.highway"]].mean()
mileage_by_manufacturer

               MPG.city  MPG.highway
Manufacturer
Acura            22.500    28.000000
Audi             21.500    26.000000
BMW              24.000    30.000000
Buick            21.000    27.750000
Cadillac         18.000    25.000000
Chevrolet        21.125    27.625000
Chrylser         22.000    28.000000
Chrysler         22.500    27.000000
Dodge            23.000    26.833333
Eagle            25.500    30.500000
Ford             23.250    28.125000
Geo              38.000    43.000000
Honda            30.000    36.000000
Hyundai          25.250    30.750000
Infiniti         19.000    22.000000
Lexus            20.000    23.500000
Lincoln          19.500    26.000000
Mazda            24.400    31.200000
Mercedes-Benz    21.500    27.000000
Mercury          22.000    26.000000
Mitsubishi       24.500    28.500000
Nissan           23.750    28.000000
Oldsmobile       22.000    28.250000
Plymouth         23.000    30.000000
Pontiac          23.400    31.000000
Saab             22.000    26.000000
Saturn           28.000    38.000000
Subaru           27.000    32.333333
Suzuki           39.000    43.000000
Toyota           25.250    30.000000
Volkswagen       21.750    27.250000
Volvo            22.500    28.000000

find the any weight of cars of type small

FIRST METHOD

In [ ]:
df[df["Type"]=="Small"]["Weight"].mean()

np.float64(2312.8571428571427)

SECOND METHOD

In [ ]:
Small = df[df["Type"]=="Small"]

In [ ]:
Small["Weight"].mean()

np.float64(2312.8571428571427)

find the horsepower and enginesize top 10 cars

In [ ]:
TOP = df[["Manufacturer","EngineSize","Horsepower"]].sort_values("Horsepower").head(10)
TOP

   Manufacturer  EngineSize  Horsepower
38          Geo         1.0          55
30         Ford         1.3          63
82       Suzuki         1.3          70
79       Subaru         1.2          73
72      Pontiac         1.6          74
87   Volkswagen         1.8          81
43      Hyundai         1.5          81
52        Mazda         1.6          82
83       Toyota         1.5          82
78       Saturn         1.9          85

In [ ]:
car = df[df["Origin"]=="non-USA"]
car

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9,12036
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,20,25,Driver only,...,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5,13845
2,3,Audi,90,Compact,25.9,29.1,32.3,22,26,Driver only,...,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4,12060
3,4,Audi,100,Midsize,30.8,37.7,44.6,21,26,Driver only,...,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8,13510
4,5,BMW,535i,Midsize,23.7,30.0,36.2,24,30,Driver only,...,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5,12834
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,Driver only,...,93,63,34,26.5,14.0,1695,non-USA,Geo Metro,3.3,9513
39,40,Geo,Storm,Sporty,11.5,12.5,13.5,30,36,Driver only,...,97,67,37,26.5,14.0,2475,non-USA,Geo Storm,2.0,10988
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver only,...,100,70,39,26.5,14.0,2865,non-USA,Honda Prelude,5.7,12250
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,103,67,36,26.5,14.0,2350,non-USA,Honda Civic,7.4,11591
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver only,...,107,67,41,26.5,14.0,3040,non-USA,Honda Accord,7.4,12395
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,Driver only,...,94,63,35,26.5,14.0,2345,non-USA,Hyundai Excel,2.4,10584
44,45,Hyundai,Elantra,Small,9.0,10.0,11.0,24,29,Driver only,...,98,66,36,26.5,14.0,2620,non-USA,Hyundai Elantra,2.0,11352
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,Driver only,...,94,64,34,26.5,14.0,2285,non-USA,Hyundai Scoupe,1.9,10624
46,47,Hyundai,Sonata,Midsize,12.4,13.9,15.3,22,27,Driver only,...,104,69,41,26.5,14.0,2885,non-USA,Hyundai Sonata,2.9,12696
47,48,Infiniti,Q45,Midsize,45.4,47.9,50.4,19,22,Driver only,...,113,72,42,26.5,14.0,4000,non-USA,Infiniti Q45,5.0,14400
48,49,Lexus,ES300,Midsize,27.5,28.0,28.4,20,24,Driver only,...,103,70,40,26.5,14.0,3510,non-USA,Lexus ES300,0.9,13160
49,50,Lexus,SC300,Midsize,34.7,35.2,35.6,20,23,Driver only,...,106,71,39,26.5,14.0,3515,non-USA,Lexus SC300,0.9,13561
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,Driver only,...,97,66,34,26.5,14.0,2325,non-USA,Mazda 323,1.7,10824
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,Driver only,...,98,66,36,26.5,14.0,2440,non-USA,Mazda Protege,1.4,11352
54,55,Mazda,626,Compact,14.3,16.5,18.7,26,34,Driver only,...,103,69,40,26.5,14.0,2970,non-USA,Mazda 626,4.4,12696
55,56,Mazda,MPV,Van,16.6,19.1,21.7,20,24,Driver only,...,110,72,39,26.5,14.0,3735,non-USA,Mazda MPV,5.1,13680
56,57,Mazda,RX-7,Sporty,32.5,32.5,32.5,19,25,Driver only,...,96,69,37,26.5,14.0,2895,non-USA,Mazda RX-7,0.0,11661
57,58,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,22,29,Driver only,...,105,67,34,26.5,14.0,2920,non-USA,Mercedes-Benz 190E,5.9,11725
58,59,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,21,25,Driver only,...,110,69,37,26.5,14.0,3525,non-USA,Mercedes-Benz 300E,36.2,12903
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,Driver only,...,98,67,36,26.5,14.0,2295,non-USA,Mitsubishi Mirage,5.2,11524
62,63,Mitsubishi,Diamante,Midsize,22.4,26.1,29.9,20,24,Driver only,...,107,70,43,26.5,14.0,3730,non-USA,Mitsubishi Diamante,7.5,13300
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,96,66,33,26.5,14.0,2545,non-USA,Nissan Sentra,6.2,11220
64,65,Nissan,Altima,Compact,13.0,15.7,18.3,24,30,Driver only,...,103,67,40,26.5,14.0,3050,non-USA,Nissan Altima,5.3,12127
65,66,Nissan,Quest,Van,16.7,19.1,21.5,19,23,Driver only,...,112,74,41,26.5,14.0,4100,non-USA,Nissan Quest,4.8,14060
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,23,26,Driver only,...,104,69,41,26.5,14.0,3200,non-USA,Nissan Maxima,1.0,12972
77,78,Saab,900,Compact,20.3,28.7,37.1,22,26,Driver only,...,99,67,37,26.5,14.0,2775,non-USA,Saab 900,16.8,12328
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,Driver only,...,90,60,32,26.5,14.0,2045,non-USA,Subaru Justy,2.2,8760
80,81,Subaru,Loyale,Small,10.5,10.9,11.3,25,30,Driver only,...,97,65,35,26.5,14.0,2490,non-USA,Subaru Loyale,0.8,11375
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,102,67,37,26.5,14.0,3085,non-USA,Subaru Legacy,6.4,11993
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,Driver only,...,93,63,34,26.5,14.0,1965,non-USA,Suzuki Swift,2.7,10143
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,94,65,36,26.5,14.0,2055,non-USA,Toyota Tercel,4.0,10530
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,99,69,39,26.5,14.0,2950,non-USA,Toyota Celica,8.4,12006
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,24,29,Driver only,...,103,70,38,26.5,14.0,3030,non-USA,Toyota Camry,6.0,13160
86,87,Toyota,Previa,Van,18.9,22.7,26.6,20,22,Driver only,...,113,71,41,26.5,14.0,3785,non-USA,Toyota Previa,7.7,13277
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,Driver only,...,93,63,34,26.5,14.0,2240,non-USA,Volkswagen Fox,0.8,10269
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,19,21,Driver only,...,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1,13464
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,23,30,Driver only,...,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8,12060
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,20,25,Driver only,...,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8,10494
91,92,Volvo,240,Compact,21.8,22.7,23.5,23,28,Driver only,...,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7,12730
92,93,Volvo,850,Midsize,24.8,26.7,28.5,22,28,Driver only,...,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7,12696

In [ ]:
car.sort_values("MPG.city",ascending=False)
car

,Id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,difference,Area
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,Driver only,...,102,68,37,26.5,14.0,2705,non-USA,Acura Integra,5.9,12036
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,20,25,Driver only,...,115,71,38,26.5,14.0,3560,non-USA,Acura Legend,9.5,13845
2,3,Audi,90,Compact,25.9,29.1,32.3,22,26,Driver only,...,102,67,37,26.5,14.0,3375,non-USA,Audi 90,6.4,12060
3,4,Audi,100,Midsize,30.8,37.7,44.6,21,26,Driver only,...,106,70,37,26.5,14.0,3405,non-USA,Audi 100,13.8,13510
4,5,BMW,535i,Midsize,23.7,30.0,36.2,24,30,Driver only,...,109,69,39,26.5,14.0,3640,non-USA,BMW 535i,12.5,12834
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,Driver only,...,93,63,34,26.5,14.0,1695,non-USA,Geo Metro,3.3,9513
39,40,Geo,Storm,Sporty,11.5,12.5,13.5,30,36,Driver only,...,97,67,37,26.5,14.0,2475,non-USA,Geo Storm,2.0,10988
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver only,...,100,70,39,26.5,14.0,2865,non-USA,Honda Prelude,5.7,12250
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,103,67,36,26.5,14.0,2350,non-USA,Honda Civic,7.4,11591
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver only,...,107,67,41,26.5,14.0,3040,non-USA,Honda Accord,7.4,12395
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,Driver only,...,94,63,35,26.5,14.0,2345,non-USA,Hyundai Excel,2.4,10584
44,45,Hyundai,Elantra,Small,9.0,10.0,11.0,24,29,Driver only,...,98,66,36,26.5,14.0,2620,non-USA,Hyundai Elantra,2.0,11352
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,Driver only,...,94,64,34,26.5,14.0,2285,non-USA,Hyundai Scoupe,1.9,10624
46,47,Hyundai,Sonata,Midsize,12.4,13.9,15.3,22,27,Driver only,...,104,69,41,26.5,14.0,2885,non-USA,Hyundai Sonata,2.9,12696
47,48,Infiniti,Q45,Midsize,45.4,47.9,50.4,19,22,Driver only,...,113,72,42,26.5,14.0,4000,non-USA,Infiniti Q45,5.0,14400
48,49,Lexus,ES300,Midsize,27.5,28.0,28.4,20,24,Driver only,...,103,70,40,26.5,14.0,3510,non-USA,Lexus ES300,0.9,13160
49,50,Lexus,SC300,Midsize,34.7,35.2,35.6,20,23,Driver only,...,106,71,39,26.5,14.0,3515,non-USA,Lexus SC300,0.9,13561
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,Driver only,...,97,66,34,26.5,14.0,2325,non-USA,Mazda 323,1.7,10824
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,Driver only,...,98,66,36,26.5,14.0,2440,non-USA,Mazda Protege,1.4,11352
54,55,Mazda,626,Compact,14.3,16.5,18.7,26,34,Driver only,...,103,69,40,26.5,14.0,2970,non-USA,Mazda 626,4.4,12696
55,56,Mazda,MPV,Van,16.6,19.1,21.7,20,24,Driver only,...,110,72,39,26.5,14.0,3735,non-USA,Mazda MPV,5.1,13680
56,57,Mazda,RX-7,Sporty,32.5,32.5,32.5,19,25,Driver only,...,96,69,37,26.5,14.0,2895,non-USA,Mazda RX-7,0.0,11661
57,58,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,22,29,Driver only,...,105,67,34,26.5,14.0,2920,non-USA,Mercedes-Benz 190E,5.9,11725
58,59,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,21,25,Driver only,...,110,69,37,26.5,14.0,3525,non-USA,Mercedes-Benz 300E,36.2,12903
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,Driver only,...,98,67,36,26.5,14.0,2295,non-USA,Mitsubishi Mirage,5.2,11524
62,63,Mitsubishi,Diamante,Midsize,22.4,26.1,29.9,20,24,Driver only,...,107,70,43,26.5,14.0,3730,non-USA,Mitsubishi Diamante,7.5,13300
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,96,66,33,26.5,14.0,2545,non-USA,Nissan Sentra,6.2,11220
64,65,Nissan,Altima,Compact,13.0,15.7,18.3,24,30,Driver only,...,103,67,40,26.5,14.0,3050,non-USA,Nissan Altima,5.3,12127
65,66,Nissan,Quest,Van,16.7,19.1,21.5,19,23,Driver only,...,112,74,41,26.5,14.0,4100,non-USA,Nissan Quest,4.8,14060
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,23,26,Driver only,...,104,69,41,26.5,14.0,3200,non-USA,Nissan Maxima,1.0,12972
77,78,Saab,900,Compact,20.3,28.7,37.1,22,26,Driver only,...,99,67,37,26.5,14.0,2775,non-USA,Saab 900,16.8,12328
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,Driver only,...,90,60,32,26.5,14.0,2045,non-USA,Subaru Justy,2.2,8760
80,81,Subaru,Loyale,Small,10.5,10.9,11.3,25,30,Driver only,...,97,65,35,26.5,14.0,2490,non-USA,Subaru Loyale,0.8,11375
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,102,67,37,26.5,14.0,3085,non-USA,Subaru Legacy,6.4,11993
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,Driver only,...,93,63,34,26.5,14.0,1965,non-USA,Suzuki Swift,2.7,10143
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,94,65,36,26.5,14.0,2055,non-USA,Toyota Tercel,4.0,10530
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,99,69,39,26.5,14.0,2950,non-USA,Toyota Celica,8.4,12006
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,24,29,Driver only,...,103,70,38,26.5,14.0,3030,non-USA,Toyota Camry,6.0,13160
86,87,Toyota,Previa,Van,18.9,22.7,26.6,20,22,Driver only,...,113,71,41,26.5,14.0,3785,non-USA,Toyota Previa,7.7,13277
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,Driver only,...,93,63,34,26.5,14.0,2240,non-USA,Volkswagen Fox,0.8,10269
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,19,21,Driver only,...,115,72,38,26.5,14.0,3960,non-USA,Volkswagen Eurovan,6.1,13464
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,23,30,Driver only,...,103,67,35,26.5,14.0,2985,non-USA,Volkswagen Passat,4.8,12060
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,20,25,Driver only,...,97,66,36,26.5,14.0,2810,non-USA,Volkswagen Corrado,0.8,10494
91,92,Volvo,240,Compact,21.8,22.7,23.5,23,28,Driver only,...,104,67,37,26.5,14.0,2985,non-USA,Volvo 240,1.7,12730
92,93,Volvo,850,Midsize,24.8,26.7,28.5,22,28,Driver only,...,105,69,38,26.5,14.0,3245,non-USA,Volvo 850,3.7,12696

In [ ]:
from numpy._core.defchararray import index
df.pivot_table(index ="Manufacturer",
columns="Type",
values="Price",
aggfunc="mean")

Type           Compact  Large  Midsize  Small  Sporty    Van
Manufacturer
Acura              NaN    NaN     33.9  15.90     NaN    NaN
Audi              29.1    NaN     37.7    NaN     NaN    NaN
BMW                NaN    NaN     30.0    NaN     NaN    NaN
Buick              NaN  22.25     21.0    NaN     NaN    NaN
Cadillac           NaN  34.70     40.1    NaN     NaN    NaN
Chevrolet         12.4  18.80     15.9    NaN   26.55  16.45
Chrylser           NaN  18.40      NaN    NaN     NaN    NaN
Chrysler          15.8  29.50      NaN    NaN     NaN    NaN
Dodge             13.3    NaN     15.6  10.25   25.80  19.00
Eagle              NaN  19.30      NaN  12.20     NaN    NaN
Ford              11.3  20.90     20.2   8.75   14.95  19.90
Geo                NaN    NaN      NaN   8.40   12.50    NaN
Honda             17.5    NaN      NaN  12.10   19.80    NaN
Hyundai            NaN    NaN     13.9   9.00   10.00    NaN
Infiniti           NaN    NaN     47.9    NaN     NaN    NaN
Lexus              NaN    NaN     31.6    NaN     NaN    NaN
Lincoln            NaN  36.10     34.3    NaN     NaN    NaN
Mazda             16.5    NaN      NaN   9.95   32.50  19.10
Mercedes-Benz     31.9    NaN     61.9    NaN     NaN    NaN
Mercury            NaN    NaN     14.9    NaN   14.10    NaN
Mitsubishi         NaN    NaN     26.1  10.30     NaN    NaN
Nissan            15.7    NaN     21.5  11.80     NaN  19.10
Oldsmobile        13.5  20.70     16.3    NaN     NaN  19.50
Plymouth           NaN    NaN      NaN    NaN   14.40    NaN
Pontiac           11.1  24.40     18.5   9.00   17.70    NaN
Saab              28.7    NaN      NaN    NaN     NaN    NaN
Saturn             NaN    NaN      NaN  11.10     NaN    NaN
Subaru            19.5    NaN      NaN   9.65     NaN    NaN
Suzuki             NaN    NaN      NaN   8.60     NaN    NaN
Toyota             NaN    NaN     18.2   9.80   18.40  22.70
Volkswagen        20.0    NaN      NaN   9.10   23.30  19.70
Volvo             22.7    NaN     26.7    NaN     NaN    NaN